### ISSUE TITLE
Ontology (meta) changes, documentation, and hosting

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#387]
In GitLab by @han.kruiger.tno.nl on Jun 14, 2022, 08:29

- [x] Rename ontology to Knowledge Engine Ontology (including label)
- [x] Change the URLs in the ontology to use `https://w3id.org/knowledge-engine/` as the base URI.
  - [x] ~~Do we use `/` or `#`? I think `#` has problems with this redirect method.~~ We will use `/`.
- [x] ~~Figure out the target of the redirect. (Where will we host the ontology + documentation?)~~ `www.knowledge-engine.eu/ontology/`
- [x] Generate documentation with Widoco and host it at `www.knowledge-engine.eu/ontology/`
  - [x] Additions should be made to the ontology to complete certain parts of the generated documentation
- [x] Register the redirect at https://w3id.org

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Jun 14, 2022, 12:07

marked the checklist item **Rename ontology to Knowledge Engine Ontology (including label)** as completed

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Jun 14, 2022, 12:29

created branch [`373-ontology-meta-changes-documentation-and-hosting`](/interconnect/knowledge-engine/-/compare/master...373-ontology-meta-changes-documentation-and-hosting) to address this issue

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Nov 18, 2022, 15:02

marked the checklist item **Generate documentation with Widoco and host it at `www.knowledge-engine.eu/ontology/`** as completed

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Nov 18, 2022, 15:02

marked the checklist item **Additions should be made to the ontology to complete certain parts of the generated documentation** as completed

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Nov 18, 2022, 16:51

marked the checklist item **Register the redirect at https://w3id.org** as completed

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Nov 18, 2022, 16:51

https://w3id.org/knowledge-engine/ works now! :tada:
