### ISSUE TITLE
interconnect.ke.sc.MetaKnowledgeBaseImpl.isMetaKnowledgeInteraction(URI) should use the MyKnowledgeBaseStore to determine whether something is a meta interaction or not.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#96]
In GitLab by @barry.nouwt.tno.nl on Jan 29, 2021, 08:37

~~Also, remove the META URI SUFFIX (see interconnect.ke.sc.MetaKnowledgeBaseImpl.ASK_SUFFIX) and the ANSWER version from the code and replace those with generated URI like the ones initiated from the Knowledge Base.~~

Also, replace interconnect.ke.sc.MyKnowledgeBaseStoreImpl.register(MyKnowledgeInteractionInfo) with a boolean isMeta on all other register methods, because we do not want The KnowledgeInteractionInfo objects to be managed somewhere else than the MyKnowledgeBaseStoreImpl.

Tasks:

- [x] Rename `MyKnowledgeBaseStore`(`Impl`) to `KnowledgeBaseStore`(`Impl`)
- [x] Add `isMeta` boolean.
- [x] Make sure only `MyKnowledgeBaseStoreImpl` creates `KnowledgeInteractionInfo` objects (and their IDs)
- [ ] ~~Remove meta suffixes and see where stuff breaks (always assume that stuff breaks)~~ (Turned out not possible)
- [ ] ~~Fix the stuff that breaks~~ (Nothing broke!)

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Jan 29, 2021, 14:35

marked the checklist item **Add `isMeta` boolean.** as completed

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Jan 29, 2021, 14:35

marked the checklist item **Make sure only `MyKnowledgeBaseStoreImpl` creates `KnowledgeInteractionInfo` objects (and their IDs)** as completed

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Jan 29, 2021, 14:38

I had to change the `KnowledgeBaseStore` interface, and added a method `public URI getMetaId(URI knowledgeBaseId, KnowledgeInteractionInfo.Type kiType)` where the logic lives for the hardcoded KI IDs.

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Jan 29, 2021, 14:39

mentioned in commit 1c8eb8f76566b968b4a5891fbaaf0bd13e33c821
